import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div className='h-full'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div className='flex justify-center items-center'>
        <div> Page d&apos;accueil </div>
      </div>
      </div>
    </div>
  )
}

export default Home
